version: '3.8'

services:
  dve_shkatulki:
    hostname: dve_shkatulki
    container_name: dve_shkatulki
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped