export function getGift() {
  const images = [
    'airplane.png',
    'bag.png',
    'baggage.png',
    'baggage2.png',
    'baloon.png',
    'bball.png',
    'bike.png',
    'bottle.png',
    'car.png',
    'cat2.png',
    'cheese.png',
    'cherry.png',
    'chicken.png',
    'coconut.png',
    'coffee.png',
    'cookie.png',
    'cowboy.png',
    'dog2.png',
    'duck.png',
    'frog.png',
    'glintvein.png',
    'guitar.png',
    'hotdog.png',
    'house.png',
    'icecream.png',
    'key.png',
    'lemon.png',
    'light.png',
    'light2.png',
    'mask.png',
    'money.png',
    'octopus.png',
    'pc.png',
    'photo.png',
    'pickles.png',
    'pigeon.png',
    'ploskogubcy.png',
    'pokeball.png',
    'popcorn.png',
    'pumpkin.png',
    'retroplayer.png',
    'rocket.png',
    'sandwich.png',
    'scooter2.png',
    'soda.png',
    'submarine.png',
    'tetris.png',
    'turtle.png',
    'uno.png',
    'waterlemon.png',
  ]

  const randomIndex = Math.floor(Math.random() * images.length)
  return images[randomIndex]
}
